### ISSUE TITLE
No documentation on manual scale-up/scale-down processes

### ISSUE THREAD

**Issue by mike-evans** [Metaswitch/clearwater-docs#20]
In particular, I couldn't find any documentation describing quiescing nodes when scaling down, so it seems like we need comprehensive documentation on this for people wanting to integrate with their own orchestration tools.

**Comment by rkd-msw** [comment]
We do now have this - https://clearwater.readthedocs.org/en/latest/Clearwater_Elastic_Scaling/index.html#if-you-did-a-manual-install.
